version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    env_file:
      - db_config.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - db_config.env
