# Generated by Django 3.0.3 on 2020-02-17 23:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('specialAttack', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLevel',
            fields=[
                ('level', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('property', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('missionNum', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('currency', models.IntegerField()),
                ('backpack', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db.Backpack')),
                ('characters', models.ManyToManyField(blank=True, to='db.Character')),
                ('missionNum', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='db.Mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='monsters',
            field=models.ManyToManyField(to='db.Monster'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db.CharacterLevel'),
        ),
        migrations.AddField(
            model_name='backpack',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db.Item'),
        ),
    ]
